# nombre del workflow/pipeline
name: primer-workflow 

# evento que desencadena el workflow 
on: [push] 

# los jobs/stages que se van a ejecutar en el workflow 
jobs:

  # job name
  mi-primer-job:

    # REQUERIDO - indicamos donde va a correr el job
    runs-on: ubuntu-latest

    #Pasos que se ejecutan en el job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm version
      - run: npm install -g bats
      - run: bats -v
      - run: sleep 20
   
  mi-segundo-job:

    # REQUERIDO - indicamos donde va a correr el job
      runs-on: ubuntu-latest

    # Indica dependencia este job de otro
      needs: mi-primer-job

    #Pasos que se ejecutan en el job
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
           node-version: '14'
        - run: npm version
        - run: npm install -g bats
        - run: bats -v
